### PR TITLE
Poca functions

### PR DESCRIPTION
**Pull request by defc0n**
This should add support for all four `poca_*` functions.

### CODE REVIEW

**Comment by tobiemh** [comment]
Thanks for this @defc0n !

**Comment by defc0n** [comment]
@tobiemh is there any likelihood of pdflib10 support being added? One issue I found with trying to do that is some of the prior functions that exist in both pdflib8 and pdflib9 and which are defined in `golang.c` have been removed completely.

**Comment by tobiemh** [comment]
Hi @defc0n it shouldn't be a problem adding pdflib10 support - it would just need the main.go file to be completely split out depending on the version + operating system I think. This commit is probably a good starting point for that ... https://github.com/abcum/pdflib/commit/ed68eb5e964156a80ddf3147b99bdd052caba7a6

The only issue I foresee currently, is the base 'include' folder, which would need to be different when using tags to define the pdflib version.

What are your thoughts?

**Comment by defc0n** [comment]
I think I understand better now--I'll see where I get with. At the end of the day, I'd end up wanting to do:
```
import (
    pdflib "github.com/abcum/pdflib/pdflib10"
)
```

**Comment by tobiemh** [comment]
Yeah so that change introduced separate folders/packages so that the specific package could be imported in an environment which didn't support tags on installation (for instance Google Cloud Functions).

Technically this library operates in both ways - with tags, and with specific package import paths. Keeping both would be ideal, but that's where the difficulty lies...

**Comment by tobiemh** [comment]
So this should already be possible (and adding a pdflib10 folder should be doable) ...

```
import (
    pdflib "github.com/abcum/pdflib/pdflib9"
)
```

**Comment by defc0n** [comment]
> So this should already be possible (and adding a pdflib10 folder should be doable) ...
> 
> ```
> import (
>     pdflib "github.com/abcum/pdflib/pdflib9"
> )
> ```

Yep I just tried that out myself locally (although I had to add a go.mod file for it). I think I may be of the opinion that you should always require/specify which pdflib version you want to use in your import by pointing it to the version folder.

**Comment by defc0n** [comment]
Believe I'm fairly close to getting this to work, although I believe this build error is due to my gcc (4.8.5) being too old with their provided library in pdflib10:
```
filteredbrk.cpp:(.text+0x178b): undefined reference to `__cxa_throw_bad_array_new_length'
locavailable.cpp:(.text+0x70b): undefined reference to `__cxa_throw_bad_array_new_length'
ucharstriebuilder.cpp:(.text+0x8fe): undefined reference to `__cxa_throw_bad_array_new_length'
GlyphPositionAdjustments.cpp:(.text+0x93): undefined reference to `__cxa_throw_bad_array_new_length'
GlyphPositionAdjustments.cpp:(.text+0x209): undefined reference to `__cxa_throw_bad_array_new_length'
../my-pdflib/pdflib10/lib/libpdf-linux.a(GlyphPositionAdjustments.o):GlyphPositionAdjustments.cpp:(.text+0x2c9): more undefined references to `__cxa_throw_bad_array_new_length' follow
```

**Comment by tobiemh** [comment]
@defc0n did you get any further on that issue?

**Comment by defc0n** [comment]
> @defc0n did you get any further on that issue?

It will be later in the year before we have transitioned to a newer operating system which has a new enough version of gcc provided in a standard installation which can compile against the pdflib10 files. The workaround until then is just to use pdflib9 with an older version of the adobe acrobat block plugin. I doubt I’ll try working on it until we are on the newer OS.

**Comment by defc0n** [comment]
@tobiemh fwiw, I am able to build against pdflib10 with some code I added in my fork at https://github.com/defc0n/pdflib. I just import "github.com/defc0n/pdflib/pdflib10". No clue if it will successfully build in environments other than linux. I didn't change any of the other files outside of the pdflib10 directory. It has some functions removed which appear to no longer exist which did in 8/9.

**Pull request merged**
