### PR TITLE
Add pdflib9 support for Alpine Linux

### PR DESCRIPTION
**Pull request by naueramant**
Added amd64 architecture support to make the library work in Alpine Linux.

### CODE REVIEW

**Comment by tobiemh** [comment]
Hi @naueramant,

Thanks for this!

As I understand it, pdflib already supports amd64 architecture within its normal releases. The Alpine Linux build is for `musl libc (instead of glibc)`. Is the library you've added the specific Alpine Linux library from the following link? https://www.pdflib.com/binaries/PDFlib/920/PDFlib-9.2.0-Alpine-Linux-x86_64-C-C++.tar.gz

If so, I'd rather add a go build flag for specifically selecting an Alpine Linux version of pdflib, as there may be situations where a build might be needed for amd64, but not with Alpine Linux.

Perhaps something like the following?

```bash
go build -tags 'alpine'
```

**Comment by naueramant** [comment]
You are totally right, i forgot Alpine used musl.

Yes the library is from that link, and yes good idea to add the build tag instead.

**Comment by naueramant** [comment]
@tobiemh i have added the build tag changes.

**Comment by tobiemh** [comment]
Hey @naueramant,

Should there also be a negative build constraint `// +build !alpine` line in the `pdflib9_linux.go` file?

Otherwise I think that file also gets called when building for Alpine Linux?

**Pull request merged**
